### ISSUE TITLE
Elasticsearch 5.1.2 - authentication asking twice.

### ISSUE THREAD

**Issue by sreejithps303** [sscarduzio/elasticsearch-readonlyrest-plugin#151]
Hi,

 I am using elasticsearch and kibana 5.1.2 version. Also installed readonlyrest plugi 5.12 in elasticsearch.

When i try to access via kibana i have to give authentication twice . Anybody has this issue?
Below are the readonlyrest config in elastic search
-------------------------------------------------------------------------------------------
readonlyrest:
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden.
    access_control_rules:

    - name: Accept all requests from localhost
      type: allow
      hosts: [127.0.0.1, localhost, xx.xx.xx.xx]

    - name: "Logstash can write and create its own indices"
      auth_key: logstashauth:***********
      type: allow 

    - name: Kibana Server (full access granted via HTTP authentication)
      auth_key: reportingadmin:*************
      type: allow

    - name: Kibana Read Only User (Kibana Read Only User)
      auth_key: reporting_general:************
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*", "kafka_navigation"]

------------------------------------------------------------------------------------------------------

I have observed below  in elasticsearch logs  while login in via kibana

----------------------------------------------------------------------------------------------------------------------
[2017-01-17T11:52:58,676][INFO ][o.e.p.r.a.ACL            ]  no block has matched, forbidding by default: { id: 12e632cec7154ddb87c828f4130faa1d, type: SearchRequest, user: null, action: indices:data/read/search, OA:10.33.70.45, indices:.kibana, M:POST, P:/.kibana/index-pattern/_search, C:<OMITTED, LENGTH=39>, Headers:[x-forwarded-for=192.168.120.1, x-forwarded-port=50782, x-forwarded-proto=http, content-type=application/json, Host=10.33.70.45:9200, Connection=close, content-length=39], History:Kibana Read Only User (Kibana Read Only User)=[kibana_access=true,indices=true,auth_key=false],Accept all requests from localhost=[hosts=false],Logstash can write and create its own indices=[auth_key=false],Kibana Server (full access granted via HTTP authentication)=[auth_key=false] }

-----------------------------------------------------------------------------------------------------------------

**Comment by sscarduzio** [comment]
I acknowledge this behaviour, but on the other hand I see no misbehaviour in ReadonlyREST, as for two times it responds 401 to requests coming **without** credential.
Again something wrong Kibana, I suppose. Will dig, thanks for reporting.

**Comment by sreejithps303** [comment]
ok thanks :+1:

**Comment by sreejithps303** [comment]
Is this issue got resolved in any latest versions?

**Comment by sscarduzio** [comment]
Kibana team has definitely made some progress on this with 5.2.0, but I made them reopen the issue because they didn't fix everything.

**Comment by martin-par** [comment]
I have the same problem with version 1.13.2_es5.2.0.
I will be nice if this works someday

**Comment by gvkrf** [comment]
Hi, I'm using kibana 5.2.1 and phasing same issue.
Can any one help me is that is resolved in any version.

**Comment by sscarduzio** [comment]
UPDATE: This is a non-issue in ReadonlyREST PRO (kibana plugin) where the browser is not anymore relying on HTTP Basic Auth, but on an encrypted session cookie.

More info:
https://readonlyrest.com/pro.html

**Comment by olddanmer** [comment]
Hi! I see the issue on latest elasticsearch 5.5.0, kibana 5.5.0, readonlyrest plugin 1.16.8_es5.5.0. Is there some movement for issue decision? If problem on kibana side, is there issue in elastic bugtracker?

**Comment by anandsingh23** [comment]
@sscarduzio Hi Simone, is this the thread that you mentioned earlier?
https://github.com/elastic/kibana/issues/9583
I see a lot of interest but no developments there.

**Comment by sscarduzio** [comment]
I never tried again honestly, please test yourself or follow the kibana issue for reference. As this is not a ROR bug.
