### ISSUE TITLE
Elasticsearch service hangs in stopping status with ReadonlyREST plugin

### ISSUE THREAD

**Issue by askids** [sscarduzio/elasticsearch-readonlyrest-plugin#265]
hi,

I wasn't sure if this issue will be looked at by Elastic or ROR. So just adding the issue link here as well. Details are available in below link.

[#26483](https://github.com/elastic/elasticsearch/issues/26483)

Thanks!

**Comment by askids** [comment]
Just as I expected, Elastic has aksed to track it under ROR only and closed the issue. Steps to recreate the issue is present on the original link.

**Comment by askids** [comment]
@sscarduzio is this expected behaviour for free version of ROR? I know that security changes needs a cluster restart and I assumed that it means, restarting the ES service and NOT restarting the machine itself.

Can anyone else confirm, if they face similar issue on Windows?

**Comment by sscarduzio** [comment]
No, when we say "restart node" we always mean restart the process. 

About your issue, I know very little about windows, but I suppose the service restarter waits for the PID to disappear from the process list before launching the new process.
That means the Java process of ES is still there hanging. 

* Does it respond to queries when it's in this state?
* Can you take a thread dump of the java process while in this state?

**Comment by askids** [comment]
Ok. Let me check and get back to you on both those items.

**Comment by askids** [comment]
[dump.txt](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/files/1298326/dump.txt)

The http end point does not work once i get the error. Even in the log, it shows as node is closed (like a normal shutdown would have). I have also attached the jstack thread dump.

```
[2017-09-13T01:24:31,250][INFO ][o.e.n.Node               ] [ESURPPOC2-node1] stopping ...
[2017-09-13T01:24:31,581][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [controller/6252] [Main.cc@168] Ml controller exiting
[2017-09-13T01:24:31,586][INFO ][o.e.x.m.j.p.NativeController] Native controller process has stopped - no new native processes can be started
[2017-09-13T01:24:31,860][INFO ][o.e.n.Node               ] [ESURPPOC2-node1] stopped
[2017-09-13T01:24:31,861][INFO ][o.e.n.Node               ] [ESURPPOC2-node1] closing ...
[2017-09-13T01:24:31,926][INFO ][o.e.n.Node               ] [ESURPPOC2-node1] closed
```

**Comment by ViceIce** [comment]
Same problem here:
* Windows Server 2008 R2 SP1
* Java 8u131
* ES 5.4.3
* ROR 1.6.11

**Comment by sscarduzio** [comment]
Very difficult for me to test this. I hope the OSS community will help!

**Comment by ld57** [comment]
OKay guys, let s try to get ride of this!

I will investigate using retroactive version.

Kr 

fred

**Comment by ld57** [comment]
Hi guys, @sscarduzio fixed it in 1.16.14_pre3 :)

**Comment by askids** [comment]
Can I get a download link for this new version? I can test it on my end on v5.5.1.

**Comment by sscarduzio** [comment]
I have released a new official version, get it on the website!

**Comment by shlomi-toren-sp** [comment]
I'm using the newest version (readonlyrest-1.16.14_es5.1.1) but still getting this problem myself. Is there a fix?

**Comment by sscarduzio** [comment]
@shlomi-toren-sp will have a look, what versions are you guys using at SP? Just 5.1.1?

**Comment by shlomi-toren-sp** [comment]
Yes. ROR is the only plugin we're using.

**Comment by sscarduzio** [comment]
Yes but  are only only using ES 5.1.1? Or are you going to use newer versions of Elasticsearch as well?

**Comment by shlomi-toren-sp** [comment]
For at least the next year, 5.1.1

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sscarduzio** [comment]
@shlomi-toren-sp I've been trying this with 5.1.x. Do you read this in the logs after giving the shutdown?
```
[2018-01-17T19:26:56,403][INFO ][t.b.r.c.s.e.ESShutdownObservable] Shutting down ROR resources...
```

**Comment by shlomi-toren-sp** [comment]
[2018-01-18T00:54:22,333][INFO ][o.e.n.Node               ] [servername] stopped
[2018-01-18T00:54:22,333][INFO ][o.e.n.Node               ] [servername] closing ...
[2018-01-18T00:54:22,364][INFO ][t.b.r.c.s.e.ESShutdownObservable] Shutting down ROR resources...
[2018-01-18T00:54:22,364][INFO ][o.e.n.Node               ] [servername] closed

These are the last rows in the log




Shlomi Toren
Senior Software Engineer

[SailPoint]<http://www.sailpoint.com/>

mobile +972542090692

shlomi.toren@sailpoint.com<mailto:shlomi.toren@sailpoint.com>

www.sailpoint.com<http://www.sailpoint.com/> | careers<https://www.sailpoint.com/careers>

**Comment by sscarduzio** [comment]
@shlomi-toren-sp can you get a thread dump please? I'd like to see what threads remain hanging.

**Comment by shlomi-toren-sp** [comment]
Hey Simon, sorry for the delay.
Here’s a link to two windows process dumps: one several seconds after I stopped the process, and one a minute or so after that.
https://drive.google.com/open?id=1boq5SwVELxS0kP_zWnmjs67jGLiNyHF0




Shlomi Toren
Senior Software Engineer

[SailPoint]<http://www.sailpoint.com/>

mobile +972542090692

shlomi.toren@sailpoint.com<mailto:shlomi.toren@sailpoint.com>

www.sailpoint.com<http://www.sailpoint.com/> | careers<https://www.sailpoint.com/careers>

**Comment by sscarduzio** [comment]
@shlomi-toren-sp you passed me a file of 114 MB, are you sure you didn't send me the heap dump? I requested the thread dump:

```bash
$ kill -3 `jps |grep lasticsearch`
```

**Comment by shlomi-toren-sp** [comment]
I don’t know what that means. I sent you a windows dump of the process.
I tried following this: https://access.redhat.com/solutions/19170 but my jre folder doesn’t have “jstack.exe”.




Shlomi Toren
Senior Software Engineer

[SailPoint]<http://www.sailpoint.com/>

mobile +972542090692

shlomi.toren@sailpoint.com<mailto:shlomi.toren@sailpoint.com>

www.sailpoint.com<http://www.sailpoint.com/> | careers<https://www.sailpoint.com/careers>

**Comment by sscarduzio** [comment]
@shlomi-toren-sp if you don't have jstack, you can use JVisualVM (super useful piece of software).

<img width="846" alt="screen shot 2018-01-30 at 10 41 59" src="https://user-images.githubusercontent.com/1327189/35578648-57e1e416-05aa-11e8-8092-fee1ddffc0ec.png">

**Comment by shlomi-toren-sp** [comment]
Ok, I installed jdk on the machine but I can’t run this command. I tried:

C:\Program Files\Java\jdk-9.0.4\bin>jstack $ kill -3 `jps |grep elasticsearch`
'grep' is not recognized as an internal or external command,
operable program or batch file.

Is this windows syntax? Shouldn’t I also include the PID?



Shlomi Toren
Senior Software Engineer

[SailPoint]<http://www.sailpoint.com/>

mobile +972542090692

shlomi.toren@sailpoint.com<mailto:shlomi.toren@sailpoint.com>

www.sailpoint.com<http://www.sailpoint.com/> | careers<https://www.sailpoint.com/careers>

**Comment by shlomi-toren-sp** [comment]
Ok I may have what you wanted. I ran this:
jstack.exe -l PID >dump.txt

Did it several times in case something changes.



Shlomi Toren
Senior Software Engineer

[SailPoint]<http://www.sailpoint.com/>

mobile +972542090692

shlomi.toren@sailpoint.com<mailto:shlomi.toren@sailpoint.com>

www.sailpoint.com<http://www.sailpoint.com/> | careers<https://www.sailpoint.com/careers>

**Comment by sscarduzio** [comment]
@shlomi-toren-sp Thanks for the thread dump! I think I fixed this (although can't really test it directly).

**Comment by shlomi-toren-sp** [comment]
Thanks, I’ll give it a go!




Shlomi Toren
Senior Software Engineer

[SailPoint]<http://www.sailpoint.com/>

mobile +972542090692

shlomi.toren@sailpoint.com<mailto:shlomi.toren@sailpoint.com>

www.sailpoint.com<http://www.sailpoint.com/> | careers<https://www.sailpoint.com/careers>

**Comment by shlomi-toren-sp** [comment]
So, I’m not actually sure how I’m supposed to test this. I can only download the source code from git and not an installation zip.





Shlomi Toren
Senior Software Engineer

[SailPoint]<http://www.sailpoint.com/>

mobile +972542090692

shlomi.toren@sailpoint.com<mailto:shlomi.toren@sailpoint.com>

www.sailpoint.com<http://www.sailpoint.com/> | careers<https://www.sailpoint.com/careers>

**Comment by sscarduzio** [comment]
OK this is fixed, thanks Shlomi for reporting and testing!
