### ISSUE TITLE
BULK api calls failing when using alias

### ISSUE THREAD

**Issue by askids** [sscarduzio/elasticsearch-readonlyrest-plugin#292]
hi @sscarduzio 

We have rules defined on the base index name pattern, lets say its myindex*. The id has full access to perform all operation (no actions defined on the rule). We have alias defined as "appindexname". We ask applications to use alias for all operations. The GET calls are working fine, when we use the alias name. But the BULK api call is failing as indices rule is not matching.

I see below entry in the acl_history attribute in the ROR auditing index.
`[ServiceID->[auth_key_sha256->true, indices->false] `

Action is mentioned as indices:data/write/bulk

For now, temporarily as a workaround, we have defined an alias called myindex_alias. But this looks to be a bug.

I am running readonlyrest-1.16.13-pre1_es5.5.1 on Windows 2012. 

```
    - name: ServiceID
      type: allow
      auth_key_sha256: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      indices: ["myindex*", ".kibana*", ".elastic*", ".monitoring*",".security*",".watches*",".triggered_watches*",".watcher-history*",".readonlyrest*","readonlyrest*"]
      verbosity: error
```

Please let me know if you need any further details.

Thanks!

PS: I just noticed that there is full version 1.16.13, where as I am still on pre1. I will try to test it with the stable version and see if this is still issue is still present.

**Comment by askids** [comment]
I have tested with 1.16.13 now and getting same error. As you can see from the below ACL audit entry, ROR is not able to resolve the alias to actual index. GET operation which is using same alias works fine. But BULK API is failing.

`[ServiceID->[auth_key_sha256->true, indices->false]]`

**Comment by askids** [comment]
@sscarduzio Can you please let us know, if you have any updates on this one? Due to this issue, we aren't able to use alias with different name pattern in BULK api calls.

**Comment by askids** [comment]
@sscarduzio any updates on this issue?

**Comment by sscarduzio** [comment]
@askids, sorry for lagging on this. I postponed it because I was working with CERN folks on a possibly related issue which is now fixed in `1.16.15-pre*`. 

Can you confirm this is is still valid with the latest build?

**Comment by askids** [comment]
Yes. Its still an issue. We tried with the latest build (1.16.15-pre7) that you had provided for the TLS version support. The indices rule is shown as false and ROR rejects the bulk request.

**Comment by sscarduzio** [comment]
OK Thanks @askids

**Comment by sscarduzio** [comment]
@askids unfortunately, I'm not fully understanding this.

I'd be really grateful if you could describe a test case I can write an integration test around. Here is what I need:

* The minimal preconditions (existing indices, aliases, documents)
* A minimal configuration snippet
* A **whole** log line of a request that behaves badly
* Expected results
* Actual results

**Comment by coutoPL** [comment]
it should work in ROR 1.20.0
